#!/bin/bash

usage() {
    if [[ "$LANG" == "C.GBK" ]]; then
iconv -f 'utf-8' -t 'gbk' << EOF
作用：解压文件
    decompress <fileName>
example :
    *.tar             tar -xvf
    *.tar.gz          tar -xzf
    *.tgz             tar -xzf
    *.gz              gzip -d 或者 gunzip
    *.tar.bz2         tar -xjf
    *.bz2             bzip2 -d -k 或者 bunzip2
    *.tar.Z           tar -xZf
    *.Z               uncompress
    *.rar             unrar e
    *.zip             unzip
    *.tar.xz          tar -xvf
    *.xz              xz -d -k
EOF
    else
iconv -f 'utf-8' -t 'utf-8' << EOF
作用：解压文件
    decompress fileName
example :
    *.tar             tar -xvf
    *.tar.gz          tar -xzf
    *.tgz             tar -xzf
    *.gz              gzip -d 或者 gunzip
    *.tar.bz2         tar -xjf
    *.bz2             bzip2 -d 或者 bunzip2
    *.tar.Z           tar -xZf
    *.Z               uncompress
    *.rar             unrar e
    *.zip             unzip
    *.tar.xz          tar -xvf
    *.xz              xz -d -k
EOF
    fi
exit 0
}


case $# in
    
    0)  usage;;

    *)

    if [[ "$1" =~ \.tar$ ]]; then
        echo "  tar -xf '$@'   "
        tar -xvf $@
    elif [[ "$1" =~ \.tar.gz$ ]]; then
        echo "  tar -zxf '$@'   "
        tar -zxf $@
    elif [[ "$1" =~ \.tgz$ ]]; then
        echo "  tar -zxf '$@'   "
        tar -zxf $@
    elif [[ "$1" =~ \.gz$ ]]; then
        echo "  tar -zxf '$@'   "
        tar -zxf $@
    elif [[ "$1" =~ \.tar.bz2$ ]]; then
        echo "  tar -jxf  '$@'   "
        tar -jxf $@
    elif [[ "$1" =~ \.bz2$ ]]; then
        echo "  bzip2 -d -k '$@'   "
        bzip2 -d -k $@
    elif [[ "$1" =~ \.tar.Z$ ]]; then
        echo "  tar -zxf '$@'   "
        tar -zxf $@
    elif [[ "$1" =~ \.Z$ ]]; then
        echo "  uncompress '$@'   "
        uncompress $@
    elif [[ "$1" =~ \.rar$ ]]; then
        echo "  unrar e '$@'   "
        unrar e $@
    elif [[ "$1" =~ \.zip$ ]]; then
        echo "  unzip '$@'   "
        unzip $@
    elif [[ "$1" =~ \.tar.xz$ ]]; then
        echo "  tar -xf '$@'   "
        tar -xf $@
    elif [[ "$1" =~ \.xz$ ]]; then
        echo "  xz -d -k '$@'   "
        xz -d $@
    else
        echo "  unknow file type  "
        echo ""
    fi
    ;;
esac
