#!/usr/bin/env python3
# coding: utf-8
# original author: https://github.com/zeroleo12345

import sys, os, subprocess

def Usage():
    msg = '''Usage: find -name $2 | grep $1
example :
ff fileName: Find files

    find . -name "Makefile"

ff word .py : Find content in files

    find . -type f -name "*.[py]" | xargs -I {} sh -c "grep --color=yes -anH 'word'"

ff home -d : Find Directory

    find . -type d | grep --color=yes -anH home '''

    if os.getenv('LANG') == 'C.GBK':
        print(msg.decode('utf8'))
    else:
        print(msg)

def CheckContent():
    global content
    if content == '':
        sys.stderr.write( '[ERROR] miss content:\n\t%s\n' % ' '.join( sys.argv ) )
        sys.exit()

def db(*args):
    global g_debug
    if g_debug: print(args)

fileset = {
        'just find':[],
        'grep all object':[],
        'grep all file':[],
        'find dir':[],
        'grep some files':[],
        'grep some postfix':[],
}
content = ''
def ParseArg():
    global fileset, content, g_debug
    if '-d' in sys.argv:
        g_debug = 1
    db( sys.argv )
    if len( sys.argv ) == 1:
        Usage()
        sys.exit()
    for arg in sys.argv[1:]:
        if len( sys.argv ) == 2:
            key = 'just find'
            fileset[key].append(arg) if fileset[key] == [] else fileset[key].append(arg)
            db( key ,fileset[key] )
        elif arg == '.o':
            key = 'grep all object'
            fileset[key].append(arg) if fileset[key] == [] else fileset[key].append(arg)
            db( key ,fileset[key] )
        elif arg == '-d':
            key = 'find dir'
            fileset[key].append(arg) if fileset[key] == [] else fileset[key].append(arg)
            db( key ,fileset[key] )
        elif arg.startswith('.'):
            key = 'grep some postfix'
            fileset[key].append(arg[1:]) if fileset[key] == [] else fileset[key].append(arg[1:])
            db( key ,fileset[key] )
        elif content != '':
            key = 'grep some files'
            fileset[key].append(arg) if fileset[key] == [] else fileset[key].append(arg)
            db( key ,fileset[key] )
        elif content == '':
            content = arg
        else:

            key = 'grep all file'
            fileset[key].append(arg) if fileset[key] == [] else fileset[key].append(arg)
            db( key ,fileset[key] )

            #raise Exception('too much content:\t%s' % ' '.join(sys.argv) )

def CombiseCommand():
    global fileset, content
    if fileset['just find'] != []:
        key = 'just find'
        filename = ''.join( fileset[key] )
        if filename.startswith('..'):
            command = ''' find . -name "%s" ''' % filename[1:]
        elif filename.startswith('.'):
            command = ''' find . -name "*%s" ''' % filename
        else:
            command = ''' find . -name "%s" ''' % filename
    elif fileset['grep all object'] != []:
        key = 'grep all object'
        CheckContent()
        #alias fs="find . -type f -name '*.*o'|awk '{printf (\"nm -A %s|cat -n\n\", \$0) }'|sh|grep -a --color=yes"
        command = ''' find . -type f -name "*.o" | awk '{printf ("nm -A %%s|cat -n\\n", $0) }' | sh | grep --color=yes -anH '%s' ''' % content
    elif fileset['grep all file'] != []:
        key = 'grep all file'
        CheckContent()
        command = ''' find . -type f | xargs -I {} sh -c "grep --color=yes -anH '%s' {}" ''' % content
    elif fileset['find dir'] != []:
        key = 'find dir'
        CheckContent()
        command = ''' find . -type d | grep --color=yes -anH '%s' ''' % content
    elif len( fileset['grep some postfix'] ) != 0 or len( fileset['grep some files'] ) != 0:
        CheckContent()

        i = 0
        postfix=''
        files=''
        key = 'grep some postfix'
        if len( fileset[key] ) != 0:
            if len( fileset[key] ) == 1:
                postfix = '''-name "*.%s"''' % ''.join( fileset[key] )
                i+=1
            else:
                postfix = '''-name "*.[%s]"''' % '|'.join( fileset[key] )
                i+=1

        key = 'grep some files'
        if len( fileset[key] ) != 0:
            for f in fileset[key]:
                if i == 0:
                    files = '''-name "%s"''' % f
                    i+=1
                else:
                    files += ''' -o -name "%s"''' % f
                    i+=1
        command = ''' find . %s%s | xargs -I {} sh -c "grep --color=yes -anH '%s' {}" ''' % ( postfix, files, content )

    return command

# ADAPTED FROM: common_utils.py in https://github.com/difosschan/difoss-pybase
from subprocess import Popen, PIPE, STDOUT
import platform
# -----------------------------------------
# @return return_code, stdout, stderr
def run_shell( cmd_str, cwd=None ):
    close_fds = not (platform.system() == 'Windows') # WTF: `close_fds=True` is not supported on Windows!
    py_ver = [ int(x) for x in platform.python_version().split('.') ]
    if py_ver[0] >= 3 and py_ver[1] > 9:
            p = Popen(cmd_str, shell=True, stdout=PIPE, stderr=PIPE, close_fds=close_fds, cwd=cwd)
    else:
        p = Popen(cmd_str, shell=True, stdout=PIPE, stderr=PIPE, close_fds=close_fds, cwd=cwd, encoding='utf-8')

    p.wait()
    stdout_data, stderr_data = p.communicate()

    if py_ver[0] >= 3 and py_ver[1] > 9:
        stdout_data = stdout_data.decode('utf-8').rstrip('\n')
        stderr_data = stderr_data.decode('utf-8').rstrip('\n')
    else:
        stdout_data = stdout_data.rstrip('\n')
        stderr_data = stderr_data.rstrip('\n')

    return_code = p.returncode
    return (return_code, stdout_data, stderr_data)


def main():
    ParseArg()
    command = CombiseCommand( )
    sys.stderr.write('%s\n' % command)

    _, s, _ = run_shell(command)
    print(s)


g_debug = 0
if __name__ == "__main__":
    main()
