#!/bin/bash

result_fn="url-list.txt"

usage() {
    if [[ "$LANG" == "C.GBK" ]]; then
iconv -f 'utf-8' -t 'gbk' << EOF
作用：从 m3u8 文件中提取 ts 文件的 URL，并存在名为 $result_fn 的文件中，同时去除 m3u8 文件中的 ts 文件参数
用法：
    $(basename "$0") <http-urlprefix> [m3u8 fileName] 
EOF
    else
iconv -f 'utf-8' -t 'utf-8' << EOF
作用：从 m3u8 文件中提取 ts 文件的 URL，并存在名为 $result_fn 的文件中，同时去除 m3u8 文件中的 ts 文件参数
用法：
    $(basename "$0") <http-urlprefix> [m3u8 fileName] 
EOF
    fi
exit 0
}


case $# in
    
    0)  usage;;

    1|2)
        if [[ "$2" =~ \.m3u8 ]]; then
            m3u8_fn="$2"
        else
            m3u8_fn=$(ls *.m3u8 | head -1)
        fi
        
        echo "m3u8: $m3u8_fn"
        
        cmd="grep  '\.ts' $m3u8_fn | awk '{print \""$(echo "$1")"\"\$0}' > \"$result_fn\""
        echo "cmd: $cmd "

        # 成功后把 m3u8 文件中 .ts? 后面的字串去掉（连同“?”本身）
        eval "$cmd" && sed -i 's/\.ts\?.*/.ts/' "$m3u8_fn"
        ;;
        
esac
