#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import os,sys

argc=len(sys.argv)
if argc == 1:
    sys.stderr.write('''usage: lc <keyword>
intent: locate & hightlight the keyword (by grep).
''')
    exit(0)

key_word = sys.argv[1]

grep_extern_opt = '--color=auto'

if argc > 2:
    grep_extern_opt = ' '.join(sys.argv[2:])

cmd = ''
# 星号结尾的关键字，使用全量匹配
if key_word[len(key_word)-1] == '*':
    cmd = 'locate %s| grep %s %s' % (key_word[:-1], grep_extern_opt, key_word[:-1])
else:
    cmd = 'locate %s| grep %s -P "%s$"' % (key_word, grep_extern_opt, key_word)
sys.stderr.write(cmd + '\n')
os.system(cmd)

